# Configuration file for the Bandit security issue scanner
# https://bandit.readthedocs.io/en/latest/config.html

# Test are first included by `tests`, and then excluded by `skips`.
# If `tests` is empty, all tests are are considered included.

tests:
  #- B101
  #- B102

skips:
  - B101 # skip "assert used" check since we need assertions for pytests
