# Configuration file for Bandit
# https://bandit.readthedocs.io/en/latest/config.html

# (optional) list included tests here:
# tests: ['B201', 'B301']

# (optional) list skipped tests here:
skips: ['B101']

# B101: skip assertion check since we need these in our pytests
